### ISSUE TITLE
Invalid encoder schema generation for data classes with nullable fields

### ISSUE THREAD

**Issue by jean-helsinki** [JetBrains/kotlin-spark-api#103]
I found incorrect case in schema generator with data class nullable fields:

```kotlin
data class Sample(val optionList: List<Int>?) : Serializable

fun main() {
    val enc = encoder<Sample>()
    println(enc.schema())
}
```
gives: `StructType(StructField(optionList,ArrayType(IntegerType,false),false))`

**Comment by asm0dey** [comment]
@jean-helsinki thank you for the report. I will look into it soon! How much does it disrupt your workflow?

**Comment by nonpool** [comment]
@asm0dey i will fix this later

**Comment by jean-helsinki** [comment]
No, is non-block for me - i try to rewrite existing workflow from pyspark to native jvm stack. And kotlin-spark looks very friendly and perspective, but still buggy. 
Encoders and full udf/udaf support is very critical part for usage in production.
Maybe i can help with tests and some cases, that i find in my discovery?
I'm newbie in kotlin/scala, but i want to help.

**Comment by asm0dey** [comment]
This concrete issue is not connected to UDF/UDAF, right? It should be relatively simple to solve, I think, but I'm not sure if it really changes something

**Comment by nonpool** [comment]
This case is not connected to UDF/UDAF. I think `jean-helsinki` is the same as mine: Want to make this project better.

**Comment by jean-helsinki** [comment]
Of course his issue not affect udf/udaf's, i push new issues later.

**Comment by asm0dey** [comment]
Absolutely, and thank you very much for your help!
