### ISSUE TITLE
Hope to complete UDFRegister functions

### ISSUE THREAD

**Issue by nonpool** [JetBrains/kotlin-spark-api#104]
I think this  [pr](https://github.com/JetBrains/kotlin-spark-api/pull/67) has already completed half of the adaptation, only hack `RowEncoder` can be completed.
At present, this pr has not been updated for a long time.I very much hope to complete the rest of the adaptation. What way should i choose? create a new pr or  pull the `FelixEngl:UDFRegister` branch to continue to complete?

**Comment by nonpool** [comment]
@asm0dey @FelixEngl

**Comment by asm0dey** [comment]
@nonpool definitely new PR will be much better because the original one is pretty much abandoned AKAICS

**Comment by FelixEngl** [comment]
Yes, at the moment i don't have the time to work on that pull request. (My Task with Spark is [temporarily] suspended)
If you need any help you can contact me.
