### ISSUE TITLE
Spark 3.2.x support

### ISSUE THREAD

**Issue by hawkaa** [JetBrains/kotlin-spark-api#115]
Hi there,

Thank you for a great project!

I wonder if there are any plans to support Spark 3.2.x?

Best regards,
Håkon

**Comment by Jolanrensen** [comment]
@asm0dey

**Comment by Jolanrensen** [comment]
https://github.com/JetBrains/kotlin-spark-api/pull/116

**Comment by Jolanrensen** [comment]
https://github.com/JetBrains/kotlin-spark-api/pull/117

**Comment by asm0dey** [comment]
Fixed in 1.0.3
