### ISSUE TITLE
Release 1.0.3 on Maven Central

### ISSUE THREAD

**Issue by devictr** [JetBrains/kotlin-spark-api#139]
Hi @Jolanrensen 

I was about to try out this lib with Spark 3.2.x, but it doesn't seem like version `1.0.3` is released on Maven Central. Would it be possible to release it there?

Thanks!

**Comment by Jolanrensen** [comment]
Definitely! @asm0dey? ;)

Until then you can also download the jar from the releases manually

**Comment by devictr** [comment]
Thank you!
