### ISSUE TITLE
The withSpark helper function always specifies a master URL

### ISSUE THREAD

**Issue by wfhartford** [JetBrains/kotlin-spark-api#41]
The `withSpark` helper function has a parameter `master` which defaults to `local[*]`. When submitting a JAR to run in a spark cluster, it is common to use a spark session which has no master configured. There does not seem to be a way to use the existing `withSpark` helper function without configuring a master URL.

I am very new to the spark ecosystem, if there is a better way to do what I'm trying to do, please point me in the right direction. My workaround at present is to add my own `withSpark` function which takes a pre-configured `SparkSession`:
```kotlin
fun withSpark(session: SparkSession, func: KSparkSession.() -> Unit) {
  session.apply {
    KSparkSession(session).apply {
      func()
    }
  }.also { it.stop() }
}

fun main() {
  withSpark(SparkSession.builder().appName("Kotlin Spark Application").orCreate) {
    // Spark code
  }
}
```

**Comment by asm0dey** [comment]
Hi @wfhartford, thank you for report! Could you please verify that specifying `--master yarn` in `spark-submit` won't override master configured in application?

**Comment by asm0dey** [comment]
Also, could you please try specifing `withSpark(master = "yarn"){` in your applcation? I know, this function is not fully documented in README and I'll fix it

**Comment by wfhartford** [comment]
Specifying `withSpark(master = "yarn")` caused the driver pod to wait for a long time repeating the following message:

```
20/08/07 15:26:13 INFO Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
```

This message was encountered by another user of the spark-on-k8s operator who resolved it by removing the master option: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/992

I have not been able to try via `spark-submit`. I'm not sure how to interact with my k8s operator via an external spark-submit command. That is usually left up to the operator to invoke `spark-submit` when I create a `SparkApplication` resource via the Kubernetes API.

**Comment by asm0dey** [comment]
That's interesting! So is it something you meet only with k8s operator?

**Comment by wfhartford** [comment]
I don't think that omitting the master option is specific to the k8s operator, I was under the impression it was quite common. I'm really not familiar enough with spark to speak with any kind of authority on that though. I could probably specify the master as `k8s://https://172.19.0.1:443`, but that is very specific to the cluster I'm working on at the moment. It seems to me that if omitting it does the right thing, that's probably best. Behind the scenes, the k8s operator creates a `spark.properties` file which specifies that as the master URL.

**Comment by asm0dey** [comment]
Thank you for the request, I think that we can implement `withSpark` accepting builder fairly easy.

**Comment by asm0dey** [comment]
@wfhartford please, try version 0.3.2

**Comment by asm0dey** [comment]
Fixed by https://github.com/JetBrains/kotlin-spark-api/commit/034a0a8d3135a39479b5ae2cc3cb1a02f9097303

**Comment by wfhartford** [comment]
Thank you, that's a great addition.

**Comment by asm0dey** [comment]
Does it work for you?

**Comment by wfhartford** [comment]
Yes, that's a great fix. Thank you.
