### ISSUE TITLE
Add more Column comparison functions 

### ISSUE THREAD

**Issue by Meosit** [JetBrains/kotlin-spark-api#54]
Currently the many of the existing `Column` handy functions/operators are missing in the Kotlin API, this issue is to fulfill the gap. Here is the list of functions which can be added to the API

**Infix textual functions:**
- `infix fun Column.neq(c: Column): Column`
- `infix fun Column.geq(c: Column): Column`
- `infix fun Column.leq(c: Column): Column`
- `infix fun Column.le(c: Column): Column`
- `infix fun Column.ge(c: Column): Column`
Also need to add `infix` keyword to the existing `fun Column.eq(c: Column): Column` function

**Infix char-based functions:**
- ``infix fun Column.`>=`(c: Column): Column``
- ``infix fun Column.`<=`(c: Column): Column``
- ``infix fun Column.`>`(c: Column): Column``
- ``infix fun Column.`<`(c: Column): Column``
- ``infix fun Column.`!=`(c: Column): Column``
- ``infix fun Column.`||`(c: Column): Column``
---

Also some of the functions can be implemented via [Kotlin operator functions](https://kotlinlang.org/docs/reference/operator-overloading.html) such as `compareTo`/`multiply`/`divide`/`plus`/`minus`, but this needs to be double-checked

**Comment by lpicanco** [comment]
Can I get this one?
