### ISSUE TITLE
Scala 2.11 support

### ISSUE THREAD

**Issue by gschulze** [JetBrains/kotlin-spark-api#59]
It would be nice to have support for Scala 2.11, as the most distribution of Cloudera Hadoop (6.3.3) still uses Scala 2.11.
Moreover, [CDH 6.3.3](https://docs.cloudera.com/documentation/enterprise/6/release-notes/topics/rg_cdh_63_packaging.html#cdh_633_packaging) ships with Spark 2.4.0. Is there a specific issue that makes version 2.4.1 a hard requirement?

As far as support for both Scala 2.11 and 2.12 goes, i think this can be solved by a combination of build profiles and customized packaging. I'd be happy to contribute if desired.

**Comment by asm0dey** [comment]
Actually there is something in kotlin-scala integration which I wasn't able to workaround yet to suport scala 2.4.0.

Any ideas on better implementation of support for sifferent versions is very welcome! I think that current solution is ugly, but wasn't able to find better one

**Comment by gschulze** [comment]
Hey!
I've come up with a solution to support building for both Scala 2.11 and Scala 2.12, see https://github.com/JetBrains/kotlin-spark-api. The main issue is that artifacts for different Scala versions must have different suffixes (_2.11 and _2.12, respectively). I solved it by having two different POM files in the same directory, pulling the appropriate dependencies. Which versions get build can be controlled by two profiles, named scala-2.11 and scala-2.12, with scala-2.12 being activated by default. Unfortunately, the are still compile errors in some of the configurations, but I thought it might be worth sharing the current progress.

**Comment by asm0dey** [comment]
@gschulze thank you for effort, but the link goes to this repository. Did you mean to give link to your fork?

**Comment by asm0dey** [comment]
Generally speaking it can be solved with profiles easier: 2 profiles for Scala — 2.11 and 2.12, and 3 profiles for Spark: 2.4.0, 2.4.1 and 3.0.0. All properties can be set up by these profiles.
But trouble is releasing to maven central: we need to ship several combinations with one release and I don't understand how to do it yet.

**Comment by gschulze** [comment]
Sorry, correct location is here: https://github.com/gschulze/kotlin-spark-api/tree/feature/target-profiles
The different POM files are used for building the project with different artifact IDs. The compiled artifacts are stored in different output locations (target/scala-2.11 and target/scala-2.12). I think this way releasing two different artifacts from the same source should work.

**Comment by gschulze** [comment]
I finalized the project structure and fixed one build error in the Scala 2.11 build. Packaging of artifacts now works fine for all Scala/Spark combinations, however, some tests are still failing:

`mvn -Pscala-2.11 -Pscala-2.12 -DskipTests clean package`

**Comment by asm0dey** [comment]
@gschulze Awesome! Would you like to make a PR and let's fix test errors together?

**Comment by gschulze** [comment]
Sure: https://github.com/JetBrains/kotlin-spark-api/pull/62

It seems that the test errors are caused by Spark version 2.4.0, with 2.4.1 tests are running through. Would be awesome to have Spark 2.4.0 compatibility though.

**Comment by asm0dey** [comment]
Awesome! I'll look into it today

**Comment by asm0dey** [comment]
Your solution is sooo beautiful :heart_eyes:, thank you for it!
Regarding tests, Y

**Comment by asm0dey** [comment]
I believe part of problem is Spark 2.4.0 uses Scala 2.11 for Scala API: https://spark.apache.org/docs/2.4.0/ and 2.4.1 uses Scala 2.12 https://spark.apache.org/docs/2.4.1/

**Comment by asm0dey** [comment]
@gschulze please look at #63. WDYT?

**Comment by gschulze** [comment]
Ah, so 2.4.1+ needs to be compiled with Scala 2.12? The solution you suggested looks good to me!
Regarding profile activation, one issue that remains is that only one module should be activated by default if you are developing within IntelliJIDEA. This is currently problematic for the examples project, where the 2.4 and the 3.0 version are both active at the same time, but share the same source folders.

**Comment by asm0dey** [comment]
There is checkbox in maven tool window, which allows you to (de)activate any profiles

**Comment by asm0dey** [comment]
Thank you very much for contribution!

**Comment by gschulze** [comment]
You're welcome! Great to see Kotlin entering the Big Data world!

**Comment by asm0dey** [comment]
Thank you for warm welcome!

**Comment by asm0dey** [comment]
Will be released with next preview
