### ISSUE TITLE
Spark 3 support for arrayos of primitives

### ISSUE THREAD

**Issue by asm0dey** [JetBrains/kotlin-spark-api#65]
Currently test `should("!handle primitive arrays")` is skipped on Spark 3 cause it fails. It shout be fixed until preview2 release

**Comment by Jolanrensen** [comment]
The `encoder<T>()` function also doesn't seem to support Arrays. The `schema()` function in `ApiV1.kt` only supports Iterables, Maps and Data Classes of which Arrays are neither. It's however possible to encode Arrays either by iterating over them using their iterators or using `org.apache.spark.sql.SQLImplicits` to get the encoders.

**Comment by asm0dey** [comment]
Primitive arrays are supported. They should be declared as `intArrayOf`. `booleanArraOf` etc.
