### ISSUE TITLE
Overload resolution ambiguity 

### ISSUE THREAD

**Issue by Jolanrensen** [JetBrains/kotlin-spark-api#75]
Since `KeyValueGroupedDataset` in Scala already has the functions 
```scala
def reduceGroups(f: (V, V) => V): Dataset[(K, V)]
```
and
```scala
def reduceGroups(f: ReduceFunction[V]): Dataset[(K, V)]
```
this has priority over the extension function provided in the api:
```kotlin
inline fun <reified KEY, reified VALUE> KeyValueGroupedDataset<KEY, VALUE>.reduceGroups(noinline func: (VALUE, VALUE) -> VALUE): Dataset<Pair<KEY, VALUE>>
```

and thus makes writing 
```kotlin
groups.reduceGroups { a, b ->  ... }
```
impossible in the code due to Overload resolution ambiguity.
Currently, the only way to use the Kotlin one is by typing:
```kotlin
groups.reduceGroups(func = { a, b ->  ... })
```
(It's also confusing why this maps the values to `Pair`s instead of `Arity2`s... but that's another matter)

This problem is also relevant for `mapValues` and `mapGroups`

**Comment by asm0dey** [comment]
Could you please provide me with reproducer? Looks like these functions are tested and there are examples of usage and they compile fine…

**Comment by Jolanrensen** [comment]
> Could you please provide me with reproducer? Looks like these functions are tested and there are examples of usage and they compile fine…

It appears, there are no tests yet for these functions. I provided an example in the 3.0 test here: https://github.com/Jolanrensen/kotlin-spark-api/tree/overloadResolutionAmbiguityExample

**Comment by asm0dey** [comment]
The absence of tests looks like a major bug itself! Thank you for reporting!

**Comment by Jolanrensen** [comment]
@asm0dey 
I think currently the only solution (apart from Spark implementing first party Kotlin support or we finding new names for `reduce`, `mapValues` etc.) would be a Kotlin wrapper for these. 
Something like:
```kotlin
class KDataset<T>(dataset: Dataset<T>) : Dataset<T>(dataset.queryExecution(), dataset.encoder()) {
    
    fun reduce(func: (T, T) -> T): T = reduce(ReduceFunction(func))
    
}
```
solves the issue, but it would require a large overhaul of the entire API, plus it might add some extra complexity for the users.
(Not sure if I mentioned it before, but `Dataset.reduce` suffers from the same issue as the other methods mentioned here. They can only be called with a specific `ReduceFunction` or a named parameter to avoid the overload.)

**Comment by Jolanrensen** [comment]
@asm0dey 
I know KDataset will probably not happen, but I was bored and thought I'd give it a try, just for fun.

Here's my implementation (3.0 only, hence the errors):

https://github.com/Jolanrensen/kotlin-spark-api/tree/KDataset

And here are my thoughts:

It does provide some benefits. It can be used as a normal `Dataset` and there is an easy `toKotlin()` conversion. Every time (most time) a dataset would be created inside the Kotlin Spark API, now a `KDataset` is created.
It's more null-safe since the arguments are now supplied in Kotlin functions instead of Scala ones.
The lambda types are easier to understand when read since it's normal Kotlin notation now and not interfaces.
Most of the resolution ambiguity, like `reduce {}`, is gone. 
Not everything can be solved how we want it though, for instance, `select()` cannot return a `Dataset<Pair>`. We still need `selectTyped()` for that, however, `select()` can now be overridden and annotated with @Deprecated.
This @Deprecated annotation is also helpful for `foreach` to point to `forEach` etc.
KeyValueGroupedDataset would also need to be wrapped for the other overload resolution ambiguities.
And `KDataset` is of course more work if the Spark API itself changes.

**Comment by Jolanrensen** [comment]
@asm0dey 

Any idea why the `Dataset.filter {}` lambda works without resolution ambiguity but `Dataset.reduce {}` does not?
They both have a Java/Scala variant with an interface and a functional type version.
(I'm checking to see if more functions need a K-variant in https://github.com/Jolanrensen/kotlin-spark-api/tree/fixing-more-overload-res-ambiguity)

**Comment by Jolanrensen** [comment]
I added reduceK in https://github.com/JetBrains/kotlin-spark-api/pull/95
We'll need to take a good look if we missed any of the functions in the API that need a K-variant. Otherwise, we could maybe close this issue for now :)

**Comment by asm0dey** [comment]
> Any idea why the Dataset.filter {} lambda works without resolution ambiguity but Dataset.reduce {} does not?

No any idea! They look so similar!
