### ISSUE TITLE
Plan for Tuples/Arity's?

### ISSUE THREAD

**Issue by Jolanrensen** [JetBrains/kotlin-spark-api#76]
This is more of a future proofing question than an actual issue, but I was wondering if there was any plan regarding the use of Tuples in the library.
On the one hand, many of Sparks functions return Scala Tuples, which work fine although could use with some operator funs for destructuring and operator overloads.
On the other hand, the library provides the Arity's (odd name but sure) data classes which have the operator plus funs but there is no conversion between those and the Scala Tuples (yet, but I could create a pull request easily).
And finally there are the Kotlin Pairs and Tuples...

So what's the future plan? Personally I'd be fine with providing operator funs for the Scala Tuples and make them a bit more Kotlin friendly (I've got componentX operator funs ready to pull request if needed) and losing the Arity's. (Maybe make the c() functions create Scala Tuples too)
But currently, as user of the library, I'm constantly trying to figure out which method to use for Tuples.

**Comment by Jolanrensen** [comment]
I created a lot of extension functions for Tuples in Kotlin and created a separate repo for it [here](https://github.com/Jolanrensen/ScalaTuplesInKotlin). It provides tuple destructuring, textual accessing of values, easy extending of tuples using '+' and tuple joining using '..'.
I think it would be a very welcome extension to the library, but it might also be useful as a library on its own. 
Anyways, you can take a look and please let me know what you think and if you would change anything.

**Comment by asm0dey** [comment]
Sorry for not answering for a long time, it looks like I somehow don't receive notification from github O_O
They are already implemented here: https://github.com/JetBrains/kotlin-spark-api/blob/master/kotlin-spark-api/common/src/main/kotlin/org/jetbrains/kotlinx/spark/api/VarArities.kt

You can create unnamed tuple with shortcut function `c`

**Comment by Jolanrensen** [comment]
Like I said here https://github.com/JetBrains/kotlin-spark-api/pull/79
the Spark API can still return Tuples (like `joinWith()`), which the Kotlin Spark API can then not encode.
Also, your project might contain Java or Scala parts in which Tuples are more common, so not being able to provide an encoder for them would make interoperability worse.

**Comment by Jolanrensen** [comment]
@asm0dey (just making sure you still get the notification, I'm not trying to be pushy, I promise :P)

**Comment by asm0dey** [comment]
Getting it!

**Comment by asm0dey** [comment]
@Jolanrensen question about `joinWith`: currently we have wrappers for all the types of joins: inner, left, right, which are supported by `joinWith`. It's supposed to call those methods. Do you think it's not enough?

**Comment by Jolanrensen** [comment]
@asm0dey Oh right, I see, I think for that specific example it's alright then... 
I am however wondering why you chose to convert the value to a Pair instead of an Arity, as that then attempts to be the replacement of Scala's Tuples (this also applies to `reduceGroups`). Plus, doesn't converting back and forth from Arity/Pair to Scala Tuples in the API create unnecessary / unexpected overhead?

Another function which still returns Scala Tuples is `Dataset.select()` btw, but of course, these can be added to the Kotlin Spark API with converters.

However, my point about interoperability with Java and Scala code in the same project still holds. If a function from somewhere in the project returns a Tuple, then the Kotlin Spark API cannot use them in any of the function that require the implicit `encoder<>()`.

**Comment by asm0dey** [comment]
Well, I've selected Pair/Triple because they're idiomatic for Kotlin. And I hope that single conversion from Tuple2 to Pair costs almost nothing because of escape analysis. Do I have a place where I'm creating Scala tuple from Pair?

But yes, select creates tuples, it's true and it means you're right and we should support them in both Spark 2 and 3.

How do you think, what is the best way to implement support for tuples?

**Comment by Jolanrensen** [comment]
@asm0dey 
I see... However, Spark functions are often required to be as fast as possible so they can be scaled up. If the cost of conversion to Pairs is negligible then it's okay, but this might need some speed testing to make sure :).

I don't think you're converting to Scala Tuples at the moment, so that's good (so not back "and forth", haha).

 My idea was to at least support Tuple encoding, which I made working here: https://github.com/JetBrains/kotlin-spark-api/pull/79
 That way Tuples work in all functions that require the `encoder<>()` function. We might also require a Tuple DataType or schema, but that's where I got stuck.
 
 I see where you're coming from choosing Pairs and Triples, because they're native to Kotlin, however this does mean the user can now use Pairs, Triples, Arity's and Tuples from Scala... So that might be overwhelming in terms of options. I'm currently using my own library (https://github.com/Jolanrensen/ScalaTuplesInKotlin) which tries to make Scala's Tuples more manageable from Kotlin. That way I don't have to decide whether to use Pairs, Triples etc. Not sure if that's the way to go, but yeah. What do you think?

**Comment by asm0dey** [comment]
@Jolanrensen 

It looks like we should call Scala reflection for Product classes and obtain schema there. For example this method https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala#L712 should work with Tuples perfectly.

Would you like to try this approach?

**Comment by Jolanrensen** [comment]
@asm0dey I can give it a try perhaps!
I see this file is also mirrored as KotlinReflection.scala in the Scala part of the API. Can we also use this?

**Comment by Jolanrensen** [comment]
@asm0dey 
Tuple encoding seems to work using my pull request similar to how data classes are encoded. You can give it a look if you like :).

But what do you think about the pair/triple/arity/tuple situation?

**Comment by asm0dey** [comment]
@Jolanrensen 
PR works, but Pair of Tuples won't work, right? Looks like it should be addressed.
Speaking about Kotlin vs Scala tuples I tend to say that users generally should choose Kotlin-style tuples because they're idiomatic and easier to read for someone with more Kotlin experience.

Also, TBH, I would not recommend using anything higher than Arity5 ever because it's completely unclear what is where in such a huge tuples.

**Comment by asm0dey** [comment]
WOW, you'v solved it already!

**Comment by Jolanrensen** [comment]
@asm0dey Yess Datasets of data classes of tuples of pairs (also data classes) of data classes all work fine in theory :).

Only stuff like `Dataset<List<TupleX>>` doesn't work, but this is the same for `Dataset<List<SomeDataClass>>`, so I thought it was fine as it works as well as encoding data classes. I might create an issue for this, although I'm not sure if many people would actually use something like that.

I do agree with your statement to not have too large Tuples. That's the whole reason they were removed from Kotlin itself right? in favour of data classes...
The only advantage is that you don't need a separate named data class every time you want to pass on multiple values after mapping, reducing,... the data. 

I actually noticed that something like this works in some cases (not always):
(`stocks` is a `Dataset`)
```kotlin
stocks.map { it ->
    object {
        val a = it.stockName
        val b = it.closingPrices
    }
}.forEach { it ->
    println(it.a)
    println(it.b)
}
```
That's pretty exciting IMO, because that would mean named (sort of) tuples are possible after all!

**Comment by asm0dey** [comment]
> but this is the same for Dataset<List<SomeDataClass>>

Sounds like a bug to me and definitely should be created and fixed

> That's the whole reason they were removed from Kotlin itself right?

Abslutely!

> I actually noticed that something like this works in some cases

How is that at all possible? I mean… how does this anonymous object breaks scope limits?

**Comment by Jolanrensen** [comment]
@asm0dey Haha, well it's part of the Kotlin language I believe. Something like

```kotlin
val something = object {
    val a = 1
}
println(something.a)
```
also works, since the compiler knows `something` contains the property `a`. `something` shows up with an "unspecified type" and this is exactly how it is returned from the `map {}` function as well. If you annotate `something` with any type at all (like `Any`) then `something.a` won't work anymore because `.a` is not a property of `Any.` So it's just an anonymous object with a self-defined type.

What I find more curious though, is how `encoder<>()` manager to find an encoder for the anonymous object... Somehow it might be able to create a Java bean of it I guess? The ```.show()``` on a Dataset of objects with this anonymous type just shows something empty btw, which makes sense because Spark doesn't know (or shouldn't know yet) how to handle anonymous objects. Maybe proper support for anonymous objects could be considered? It should be possible with reflection, just like data classes are. And it would definitely be powerful, but I don't know it would/could handle stuff like functions inside of it.

**Comment by asm0dey** [comment]
> it's part of the Kotlin language, I believe

In this case — yes. But the definition inside lambda should not work this way as `it` can't be seen outside its lambda. But I get your point — maybe it's the whole new visible "synthetic" class every time. It still looks buggy to me, TBH.

And regarding proper support for anonymous objects: I don't know how this may be implemented. Empty `show` gives us a hint that maybe it works when you're running the whole computation only on master, for example. And on master, it doesn't need to serialize anything (hypothetically).

**Comment by asm0dey** [comment]
It means that hypothetically we can deserialize it using reflection, but it is definitely not the task to be implemented in the foreseeable future.

If you think this should be implemented — please create a separate issue here.

**Comment by Jolanrensen** [comment]
Yeah, I think you're right, that would be a lot of work if it is at all possible...

**Comment by Jolanrensen** [comment]
@asm0dey So as long as you only use these anonymous objects as intermediate step, they seem to work fine. You just cannot collect a dataset with an anonymous type (which sorta makes sense). You can even broadcast them (if they implement Serializable)!

**Comment by asm0dey** [comment]
Oh I believe it needs a proper testing on real cluster just to be sure. Sounds extremely dangerous to me TBH

**Comment by Jolanrensen** [comment]
@asm0dey I agree!

**Comment by asm0dey** [comment]
Closing for now, OK?

**Comment by Jolanrensen** [comment]
@asm0dey sure!
