### ISSUE TITLE
Dataset.select() support

### ISSUE THREAD

**Issue by Jolanrensen** [JetBrains/kotlin-spark-api#85]
This is something that still needs to be added to the kotlin spark api. The result must be mapped to pairs, similar to some of the other functions in the API.

If I have the time and motivation, I'll add it myself, otherwise anyone can feel free to add support if they need it :)

**Comment by Jolanrensen** [comment]
So I tried one `select()` function, but I'm again hitting the "Extension is shadowed by a member" message, just as here https://github.com/JetBrains/kotlin-spark-api/issues/75... This means we have to change the name if we want to be able to convert the result to Pairs, Triples or Arity's, otherwise the user won't be able to find the function in the API. 

@asm0dey

**Comment by asm0dey** [comment]
Looks like you're right, we should definitely add it

**Comment by asm0dey** [comment]
What do you think, maybe we need something like `selectTyped`?

**Comment by Jolanrensen** [comment]
@asm0dey yeah, that would work, but we shouldn't deviate too much from the Spark API in Java and Scala right? Plus, eventually, Spark might get actual Kotlin support which would mean that the problem goes away. So maybe it would be okay if we annotate it with a warning? 
In my personal project I just put a `K` behind these functions, to indicate it's Kotlin only and temporary, but that doesn't read very well.

**Comment by Jolanrensen** [comment]
@asm0dey How about `selectAsPair()`, `selectAsTriple()` and `selectAsArity()`?

**Comment by asm0dey** [comment]
TBH I don't like this names. There is one method in Scala API and I would prefer to keep one method in Kotlin API too, just overloaded

**Comment by Jolanrensen** [comment]
@asm0dey Makes sense, but it does give clarity what type of dataset is returned as in Scala and Java it usually returns Tuples and we want to change it to Pairs/Triple/Arity's for Kotlin. Plus, the user sometimes might prefer an Arity3 sometimes and a Triple other times.

**Comment by asm0dey** [comment]
So in the case of Tuple2, it will return Pair, in case of Tuple3 — Triple, and in all other cases Arity :)

This way it will be at the same time ±idiomatical and simple :)

**Comment by Jolanrensen** [comment]
@asm0dey I created a pull request: https://github.com/JetBrains/kotlin-spark-api/pull/88
