### ISSUE TITLE
 Maven dependency version of kotlin-spark-api-3.0.0:1.01 is not match documention

### ISSUE THREAD

**Issue by nonpool** [JetBrains/kotlin-spark-api#97]
In doucmention: 

3.0.0+ | 2.12 | kotlin-spark-api-3.0.0:1.0.1
-- | -- | --

but in code:
[kotlin-spark-api/3.0/pom_2.12.xml](https://github.com/JetBrains/kotlin-spark-api/blob/main/kotlin-spark-api/3.0/pom_2.12.xml)
 ` <artifactId>kotlin-spark-api-3.0</artifactId>`

in [maven.org](https://search.maven.org/search?q=g:org.jetbrains.kotlinx.spark):
https://search.maven.org/artifact/org.jetbrains.kotlinx.spark/kotlin-spark-api-3.0/1.0.1/jar

**Comment by nonpool** [comment]
So we should change artifactId `kotlin-spark-api-3.0` to `kotlin-spark-api-3.0.0` or change the documentation? @asm0dey

**Comment by nonpool** [comment]
@asm0dey

**Comment by asm0dey** [comment]
Thank you! Fixed :)
